name: Backend Continuous Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: sudo pip install pipenv && sudo pip install flake8

    - name: Install dependencies & running linter
      run: |
        pipenv install
        pipenv run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: sudo pip install pipenv && sudo pip install flake8

    - name: Install dependencies & run the tests
      run: |
        pipenv install
        pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: ECR login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag image and push to ecr
      env:
        IMAGE_NAME: backend
      run: |
        IMAGE_TAG=${{ github.sha::7 }}
        docker build -t ${{ env.IMAGE_NAME }} .
        docker tag ${{ env.IMAGE_NAME }}:$IMAGE_TAG ${{ secrets.BACKEND_ECR_REPOSITORY }}:$IMAGE_TAG
        docker push ${{ secrets.BACKEND_ECR_REPOSITORY }}:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Configure kubectl
      env:
        EKS_CLUSTER_NAME: cluster
      run: |
        aws sts get-caller-identity
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}
        kubectl config current-context

    - name: ECR login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Deploy kubernetes manifests
      run: |
        cd ./starter/backend/k8s
        IMAGE_TAG=${{ github.sha::7 }}
        kustomize edit set image backend=${{ secrets.BACKEND_ECR_REPOSITORY }}:$IMAGE_TAG
        kustomize build | kubectl apply -f -