name: Back-end CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: sudo pip install pipenv && sudo pip install flake8

    - name: Install dependencies & running linter
      run: |
        pipenv install
        pipenv run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: sudo pip install pipenv && sudo pip install flake8

    - name: Install dependencies & run the tests
      run: |
        pipenv install
        pipenv run test

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/backend
    env:
      AWS_ECR_REPOSITORY: mp-frontend:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build image
      run: docker build -t ${{ env.AWS_ECR_REPOSITORY }} .