name: Front-end CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/frontend
    strategy:
      matrix:
        node-version: [14, 16, 18]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: macos-latest
            node-version: 14
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies & Running linter
      run: |
        npm ci
        npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/frontend
    strategy:
      matrix:
        node-version: [14, 16, 18]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: macos-latest
            node-version: 14
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies & Run tests
      run: |
        npm ci
        npm run test

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./starter/frontend
    env:
      AWS_ECR_REPOSITORY_WEB: mp-frontend:latest
      APP_MOVIE_API_URL: http://localhost:5000
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build image
      run: docker build -t ${{ env.AWS_ECR_REPOSITORY_WEB }} --build-arg=REACT_APP_MOVIE_API_URL=${{ env.APP_MOVIE_API_URL }} .